INSERT INTO song (title, artist)
VALUES ('Blinding Lights', 'The Weeknd'),
       ('Watermelon Sugar', 'Harry Styles'),
       ('Mood (feat. iann dior)', '24kGoldn'),
       ('Someone You Loved', 'Lewis Capaldi'),
       ('Perfect', 'Ed Sheeran'),
       ('Believer', 'Imagine Dragons'),
       ('lovely (with Khalid)', 'Billie Eilish'),
       ('Circles', 'Post Malone'),
       ('Shape of You', 'Ed Sheeran'),
       ('Memories', 'Maroon 5'),
       ('Closer', 'The Chainsmokers'),
       ('bad guy', 'Billie Eilish'),
       ('Say You Won''t Let Go', 'James Arthur'),
       ('Lucid Dreams', 'Juice WRLD'),
       ('All of Me', 'John Legend'),
       ('7 rings', 'Ariana Grande'),
       ('Jocelyn Flores', 'XXXTENTACION'),
       ('goosebumps', 'Travis Scott'),
       ('Wake Me Up', 'Avicii'),
       ('ROCKSTAR (feat. Roddy Ricch)', 'DaBaby'),
       ('rockstar (feat. 21 Savage)', 'Post Malone'),
       ('Photograph', 'Ed Sheeran'),
       ('SAD!', 'XXXTENTACION'),
       ('SICKO MODE', 'Travis Scott'),
       ('Stressed Out', 'Twenty One Pilots'),
       ('Roses - Imanbek Remix', 'SAINt JHN'),
       ('The Box', 'Roddy Ricch'),
       ('The Hills', 'The Weeknd'),
       ('Sunflower - Spider-Man: Into the Spider-Verse', 'Post Malone'),
       ('Thinking out Loud', 'Ed Sheeran'),
       ('Starboy', 'The Weeknd'),
       ('Love Yourself', 'Justin Bieber'),
       ('Something Just Like This', 'The Chainsmokers'),
       ('Shallow', 'Lady Gaga'),
       ('Thunder', 'Imagine Dragons'),
       ('XO Tour Llif3', 'Lil Uzi Vert'),
       ('Take Me To Church', 'Hozier'),
       ('Happier', 'Marshmello'),
       ('"thank u, next"', 'Ariana Grande'),
       ('Counting Stars', 'OneRepublic'),
       ('Can''t Hold Us - feat. Ray Dalton', 'Macklemore & Ryan Lewis'),
       ('Señorita', 'Shawn Mendes'),
       ('God''s Plan', 'Drake'),
       ('Don''t Start Now', 'Dua Lipa'),
       ('Bohemian Rhapsody - Remastered 2011', 'Queen'),
       ('HUMBLE.', 'Kendrick Lamar'),
       ('Let Me Love You', 'DJ Snake'),
       ('Congratulations', 'Post Malone'),
       ('Stay With Me', 'Sam Smith'),
       ('Treat You Better', 'Shawn Mendes'),
       ('Uptown Funk (feat. Bruno Mars)', 'Mark Ronson'),
       ('I Like Me Better', 'Lauv'),
       ('when the party''s over', 'Billie Eilish'),
       ('Mr. Brightside', 'The Killers'),
       ('Dance Monkey', 'Tones And I'),
       ('Havana (feat. Young Thug)', 'Camila Cabello'),
       ('Better Now', 'Post Malone'),
       ('I Don''t Care (with Justin Bieber)', 'Ed Sheeran'),
       ('Unforgettable', 'French Montana'),
       ('Too Good At Goodbyes', 'Sam Smith'),
       ('Riptide', 'Vance Joy'),
       ('That''s What I Like', 'Bruno Mars'),
       ('See You Again (feat. Charlie Puth)', 'Wiz Khalifa'),
       ('One Kiss (with Dua Lipa)', 'Calvin Harris'),
       ('Heathens', 'Twenty One Pilots'),
       ('Demons', 'Imagine Dragons'),
       ('Youngblood', '5 Seconds of Summer'),
       ('Old Town Road - Remix', 'Lil Nas X'),
       ('I''m Yours', 'Jason Mraz'),
       ('Attention', 'Charlie Puth'),
       ('New Rules', 'Dua Lipa'),
       ('Sorry', 'Justin Bieber'),
       ('Don''t Let Me Down', 'The Chainsmokers'),
       ('7 Years', 'Lukas Graham'),
       ('I Like It', 'Cardi B'),
       ('I Fall Apart', 'Post Malone'),
       ('We Don''t Talk Anymore (feat. Selena Gomez)', 'Charlie Puth'),
       ('Can''t Feel My Face', 'The Weeknd'),
       ('Despacito', 'Luis Fonsi'),
       ('Psycho (feat. Ty Dolla $ign)', 'Post Malone'),
       ('Stitches', 'Shawn Mendes'),
       ('What Do You Mean?', 'Justin Bieber'),
       ('Wonderwall - Remastered', 'Oasis'),
       ('Radioactive', 'Imagine Dragons'),
       ('Eastside (with Halsey & Khalid)', 'benny blanco'),
       ('Cheerleader - Felix Jaehn Remix Radio Edit', 'OMI'),
       ('Cheap Thrills', 'Sia'),
       ('Girls Like You (feat. Cardi B) - Cardi B Version', 'Maroon 5'),
       ('Faded', 'Alan Walker'),
       ('Let Her Go', 'Passenger'),
       ('"CAN''T STOP THE FEELING! (from DreamWorks Animation''s ""TROLLS"")"', 'Justin Timberlake'),
       ('Lean On', 'Major Lazer'),
       ('Despacito - Remix', 'Luis Fonsi'),
       ('Lose Yourself', 'Eminem'),
       ('Without Me (with Juice WRLD)', 'Halsey'),
       ('One Dance', 'Drake'),
       ('Sugar', 'Maroon 5'),
       ('Emotions', 'Mark Mendy'),
       ('Cold Water', 'Major Lazer'),
       ('I Took A Pill In Ibiza - Seeb Remix', 'Mike Posner');